apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dem-gateway
  description: Gateway for DEM resources manipulation
  annotations:
    github.com/project-slug: MapColonies/dem-gateway
  tags:
    - nodejs
    - typescript
    - expressjs
    - dem
spec:
  type: service
  lifecycle: production
  owner: DEM
  system: dem-ingestion
